// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GServices {

  /// <summary>Holder for reflection information generated from GService.proto</summary>
  public static partial class GServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for GService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5HU2VydmljZS5wcm90bxIJR1NlcnZpY2VzGhZNZXNzYWdlcy9HTW9kZWxz",
            "LnByb3RvMjsKCEdTZXJ2aWNlEi8KCUlzR3JhbnRlZBIPLkdTZXJ2aWNlcy5H",
            "UmVxGg8uR1NlcnZpY2VzLkdSZXMiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GServices.GModelsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
