// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GServices {
  public static partial class GService
  {
    static readonly string __ServiceName = "GServices.GService";

    static readonly grpc::Marshaller<global::GServices.GReq> __Marshaller_GServices_GReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GServices.GReq.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GServices.GRes> __Marshaller_GServices_GRes = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GServices.GRes.Parser.ParseFrom);

    static readonly grpc::Method<global::GServices.GReq, global::GServices.GRes> __Method_IsGranted = new grpc::Method<global::GServices.GReq, global::GServices.GRes>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IsGranted",
        __Marshaller_GServices_GReq,
        __Marshaller_GServices_GRes);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GServices.GServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GService</summary>
    [grpc::BindServiceMethod(typeof(GService), "BindService")]
    public abstract partial class GServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GServices.GRes> IsGranted(global::GServices.GReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GService</summary>
    public partial class GServiceClient : grpc::ClientBase<GServiceClient>
    {
      /// <summary>Creates a new client for GService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GServices.GRes IsGranted(global::GServices.GReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IsGranted(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GServices.GRes IsGranted(global::GServices.GReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IsGranted, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GServices.GRes> IsGrantedAsync(global::GServices.GReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IsGrantedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GServices.GRes> IsGrantedAsync(global::GServices.GReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IsGranted, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_IsGranted, serviceImpl.IsGranted).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_IsGranted, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GServices.GReq, global::GServices.GRes>(serviceImpl.IsGranted));
    }

  }
}
#endregion
